<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic emessage' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Are you sure to delete this item?' => '',
  'Back to Overview' => '',
  'Create' => '',
  'Create New Item' => '',
  'Create Template' => '',
  'Delete' => '',
  'Fields with <span class="required">*</span> are required.' => '',
  'Language' => '',
  'Manage' => '',
  'Manage Templates' => '',
  'Message' => '',
  'New' => '',
  'Save' => '',
  'Templates' => '',
  'Translation' => '',
  'Translation Category' => '',
  'Update' => '',
  'Update Template' => '',
  'Your changes have been saved' => '',
  'Your changes have been saved.' => '',
);
