<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic emessage' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Adınız Soyadınız' => '',
  'Başvurduğunuz Pozisyon' => '',
  'Cep Telefon Numaranız' => '',
  'Değerlendirildi mi?' => '',
  'Dikey Listele' => '',
  'E-Posta Adresiniz' => '',
  'Facebookta Paylaş' => '',
  'Google Plusta Paylaş' => '',
  'Gönder' => '',
  'Haberi Paylaş' => '',
  'Kimlik' => '',
  'Konu' => '',
  'Mesajınız' => '',
  'Proje' => '',
  'Projeyi Paylaş' => '',
  'SONRAKİ' => '',
  'SOSYAL MEDYA' => '',
  'Twitterda Paylaş' => '',
  'Tüm hakları saklıdır.' => '',
  'Tümü' => '',
  'veya aşağıdaki formu kullan' => '',
  'Yatay Listele' => '',
  'ÖNCEKİ' => '',
  'Özgeçmiş Ekle' => '',
  'İLETİŞİM MAİLİ' => '',
);
