<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic emessage' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '"chartOptions.series" is expected to be an array.' => '',
  '"data" attribute cannot be blank' => '',
  '"grid" attribute must be an CGridView type of component' => '',
  '"model" attribute must be an CActiveRecord type of component' => '',
  '"redirectRoute" cannot be empty' => '',
  '"url" cannot be null if tooltip is required to be edited' => '',
  '"{attribute}" attribute cannot be empty.' => '',
  '"{attribute}" attribute must be defined' => '',
  '"{attribute}" cannnot be null' => '',
  '"{operation}" is an unsupported class operation.' => '',
  'Aktifleştir' => '',
  'Cancel' => '',
  'Chart' => '',
  'Column summary configuration must be an array containing a "type" element.' => '',
  'Enter' => '',
  'Error while saving record!' => '',
  'Grid' => '',
  'Home' => '',
  'Invalid request' => '',
  'Model "{model}" does not have attribute "{attribute}"' => '',
  'Model {class} rules do not allow to update attribute "{attr}"' => '',
  'Not set' => '',
  'Ok' => '',
  'Parameter "attribute" should be provided for Editable' => '',
  'Parameter "model" should be provided for Editable' => '',
  'Pasifleştir' => '',
  'Property "attribute" should be defined.' => '',
  'Property "data" should be of CModel class.' => '',
  'Property "primaryKey" should be defined.' => '',
  'Select' => '',
  'TbEditableColumn can be applied only to grid based on CActiveDataProvider' => '',
  'The "db" application component must be configured to be a CDbConnection object.' => '',
  'The "label" of a type must be defined.' => '',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => '',
  'Unauthorized request' => '',
  'Unsupported column type. Supported column types are: "{types}"' => '',
  'You need to set the "series" attribute in order to render a chart' => '',
  'You should provide modelClass in constructor of TbEditableSaver.' => '',
  'You should provide name for TbEditableColumn' => '',
);
