<?php
/**
 * 
 * Message translations.
 *
 * This file is automatically generated by 'yiic emessage' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * It has a some new files for twig component.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Ad Soyad' => '',
  'adresinden bize ulaşabilirsiniz.' => '',
  'Adınız Soyadınız' => '',
  'Aradığınız Sayfa bulunamadı. Bu sayfa sistemden silinmiş veya değiştirilmiş olabilir, anasayfaya giderek sistem üzerinden alakalı içeriği bulabilirsiniz.' => '',
  'Aradığınız sayfanın içerik tipi değiştirilmiş veya sayfa sizin erişiminiz dışında olabilir. Anasayfaya giderek sistem üzerinde erişebileceğiniz sayfaları bulabilirsiniz.' => '',
  'Bu e-postayı almanızın sebebi, birisinin bu adresle bağlantılı olan hesaba giriş yapmaya çalışması ve şifre hatırlatma talebinde bulunmasıdır.' => '',
  'Devamını Gör' => '',
  'DÖKÜMANLAR' => '',
  'E-Posta' => '',
  'E-Posta Adresiniz' => '',
  'E-Posta adresinizi yazın' => '',
  'E-Postanız için teşekkürler. En kısa sürede sizinle irtibata geçeceğiz.' => '',
  'E-Postayı Gönder' => '',
  'Eğer bunu siz talep ettiyseniz ve şifrenizi sıfırlamak istiyorsanız, lütfen aşağıdaki bağlantı adresine tıklayın.' => '',
  'Eğer tıklanmıyorsa, lütfen adresi kopyalayıp tarayıcınızın adres satırına yapıştırın.' => '',
  'Firma Adı' => '',
  'Giriş Yap' => '',
  'Giriş Yap veya Kaydol' => '',
  'GÖRSELLER' => '',
  'Gönder' => '',
  'Haberin Detayını Gör' => '',
  'Hata' => '',
  'Hatalı bir e-mail adresi veya şifre girdiniz.' => '',
  'Hesabınız hakkında sorularınız veya yardıma ihtiyacınız varsa, lütfen' => '',
  'Hızlı Ulaşım' => '',
  'Kayıt olmak istiyorum' => '',
  'Konu' => '',
  'Kullanıcı Adı' => '',
  'Kullanım Alanları' => '',
  'Merhaba' => '',
  'Mesajınız' => '',
  'olarak giriş yaptınız' => '',
  'Parola' => '',
  'Rol' => '',
  'Sistemde girdiğiniz E-Posta adresi kayıtlı değildir.' => '',
  'Size uygun makineyı bulmak için filtreyi kullanabilirsiniz.' => '',
  'Takip Edin' => '',
  'Teklif Al' => '',
  'TEKNİK BİLGİLER' => '',
  'Telefon' => '',
  'Telif hakları saklıdır' => '',
  'Tüm Ürünler' => '',
  'VİDEOLAR' => '',
  'Yeni ürünler, gelecek fuarlar ve güncel gelişmelerden haberdar olmak için e-posta listemize kayıt olun.' => '',
  'Yeni Şifreniz' => '',
  'Yeniliklerden Haberdar Olun!' => '',
  'ÇALIŞMA ŞARTLARI' => '',
  'Ücretsiz e-bülten\'e abone olmak istiyorum.' => '',
  'Ülke' => '',
  'ÜRÜN FİYATI' => '',
  'ÜRÜN HAKKINDA' => '',
  'Üye olduktan sonra sadece üyelere özel olan bilgilere (Fiyat bilgisi, Teklif isteği vb) ulaşabileceksiniz.' => '',
  'Üyeliğimi Tamamla' => '',
  'Üyeliğiniz tamamlandığında size eposta ile haber verilecektir.' => '',
  'çıkış yap' => '',
  'İletişim' => '',
  'İçeriği bulmak veya websitesi ile alakalı bir probleminiz ise bizimle iletişime geçebilirsiniz.' => '',
  'İçtenlikle,' => '',
  'Şifre sıfırlama işleminiz için talimatlar E-Posta adresinize gönderilmiştir.' => '',
  'Şifremi Unuttum!' => '',
  'Şifrenizi e-posta adresiniz veya kullanıcı adınızı aşağıdaki alana girerek sıfırlayabilirsiniz.' => '',
  'Şifrenizi Yenileyin' => '',
);
